heat_template_version: rocky # 2018-08-31

description: cPouta VM deployment

parameters:

  security_group_ports:
    type: comma_delimited_list
    label: Allowed ports
    description: List of ports to open in security group (SSH, HTTP, HTTPS)
    default: "22,80,443"

  # See all flavors: https://docs.csc.fi/cloud/pouta/vm-flavors-and-billing/ 
  instance_type:
    type: string
    label: Instance Type
    description: Flavor type for VMs
    default: standard.medium
    constraints:
      - allowed_values:
        - standard.tiny	  # VCPUs: 1 | RAM: 0.9 | Billing/h: 0.25
        - standard.small	# VCPUs: 2 | RAM: 1.9 | Billing/h: 0.5
        - standard.medium	# VCPUs: 3 | RAM: 3.9 | Billing/h: 1
        - standard.large	# VCPUs: 4 | RAM: 7.8 | Billing/h: 2
  
  # See all images: https://docs.csc.fi/cloud/pouta/images/
  pouta_images:
    type: string
    label: VM images
    description: VM images
    default: Ubuntu-24.04
    constraints:
      - allowed_values:
        - Ubuntu-24.04	
        # rocky linux

  private_network_id:
    type: string
    label: Private network id
    description: Private network id
    #hidden: true

  public_network_id:
    type: string
    label: d
    description: Public network id
    #hidden: true

resources:

  security_group_1: 
    type: OS::Neutron::SecurityGroup
    description: Security group 1
    properties: 
      name: security_group_1
      rules: 
        repeat:
          for_each:
            <%port%>: { get_param: security_group_ports}
          template: 
            protocol: tcp
            port_range_min: <%port%>
            port_range_max: <%port%>
            ethertype: IPv4
            direction: ingress

  ssh-key-1:
    type: OS::Nova::KeyPair
    properties:
      name: hot-test-key-1
      save_private_key: true

  private_network_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id } #private network ID
      security_groups: [{get_resource: security_group_1}]

  vm_1:
    type: OS::Nova::Server
    description: VM 1
    depends_on: [ssh-key-1]
    properties:
      name: test-vm
      flavor: { get_param: instance_type }
      availability_zone: nova
      key_name: { get_resource: ssh-key-1}
      networks: [ port: { get_resource: private_network_port }]
      block_device_mapping_v2:
        - device_name: vda
          image_id: { get_param: pouta_images }
          volume_size: 80
          boot_index: 0
          delete_on_termination: true # for testing purposes only
      diskConfig: AUTO

  floating_ip_1:
    type: OS::Neutron::FloatingIP
    description: floating_ip
    depends_on: vm_1
    properties:
      floating_network: { get_param: public_network_id }

  assosiation:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip_1}
      port_id: { get_resource: private_network_port }

outputs:

  private_key_1:
    description: Private key for SSH 1
    value: { get_attr: [ssh-key-1, private_key] }

  public_key_1:
    description: Public key for SSH 1
    value: { get_attr: [ssh-key-1, public_key] }

  floating_ip_1: 
    description: Floating ip address
    value: { get_attr: [floating_ip_1, floating_ip_address] }
  
#   ssh-key-2:
#     type: OS::Nova::KeyPair
#     properties:
#       name: hot-test-key-2
#       save_private_key: true

#   private_key_2:
#     value: { get_attr: [ssh-key-2, private_key] }
#     description: Private key for SSH 2